# =========================================================
# SIMPLE ARGOCD DEMO APPLICATION
# Uses the default ArgoCD project
# =========================================================

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nginx-demo
  namespace: argocd

spec:

  # Default ArgoCD project
  project: default

  source:

    # Official ArgoCD demo repository
    repoURL: https://github.com/argoproj/argocd-example-apps.git

    # Git branch
    targetRevision: HEAD

    # Application path inside repository
    path: guestbook

  destination:

    # In-cluster Kubernetes API
    server: https://kubernetes.default.svc

    # Target namespace
    namespace: demo-nginx

  syncPolicy:

    automated:

      # Remove old resources
      prune: true

      # Restore drift automatically
      selfHeal: true

    syncOptions:

      # Create namespace automatically
      - CreateNamespace=true
